version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - "5000:5000"
    networks:
      - replicated-log-network
    volumes:
      - master-data:/app/data
    container_name: master
    environment:
      - SECONDARIES=http://secondary-1:5001,http://secondary-2:5002
      - DATA-DIR=/app/data
      - SECONDARY_REQUEST_TIMEOUT=15.0 # set timeout > 10 seconds

  secondary-1:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    ports:
      - "5001:5001"
    volumes:
      - secondary1-data:/app/data
    networks:
      - replicated-log-network
    container_name: secondary-1
    depends_on:
      - master
    environment:
      - SERVER_ID=secondary-1
      - SECONDARY_PORT=5001
      - SECONDARY_HOST=secondary-1
      - REPLICATION_DELAY=5.0
      - MASTER_URL=http://master:5000
      - DATA_DIR=/app/data

  secondary-2:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    ports:
      - "5002:5002"
    volumes:
      - secondary2-data:/app/data
    networks:
      - replicated-log-network
    container_name: secondary-2
    depends_on:
      - master
    environment:
      - SERVER_ID=secondary-2
      - SECONDARY_PORT=5002
      - SECONDARY_HOST=secondary-2
      - REPLICATION_DELAY=10.0
      - MASTER_URL=http://master:5000
      - DATA_DIR=/app/data

volumes:
  master-data:
  secondary1-data:
  secondary2-data:

networks:
  replicated-log-network:
    driver: bridge